[project]
name = "naf-naf-solution-wizard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plotly>=6.5.0",
    "streamlit>=1.51.0",
]
